language: node_js
node_js:
  - "0.10"
deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password: $OPENSHIFT_PASSWORD
  app: $OPENSHIFT_APP
  domain: $OPENSHIFT_DOMAIN
  on:
    repo: WizardFactory/BlogSyncer
    branch: master
notifications:
  slack: wizardfactory:1tZT9pmQe4HiOBqPET9AdabJ
