language: node_js
node_js:
  - "0.10"
deploy:
  provider: openshift
  user: blogsync@wizardfactory.net
  password:
    secure: i0ZA7VoDC4w2HbqgyAB1keOfIv037ZfujPVIID/4YcAV4c235N02ieWrymSILcULVbLDpYouAaDjext/crWyW57+4SrP/TpYgPBQFgKGrcVyaG6CIreJb5nSefUw3hImnMUvxmhjSLQbhyCPG48jWeFeFdjVu4thp26T7V17bnH3OUtQxCk9q5oWRtFosBrcOlWKCEPs8XieImE1J4g2vts4NiKTvAFJ+5N4Ar/JzEuhj4bqaDbKvvlXVpvKv/7Qmh6W7kFFeLtwzAGI9CGrhQjV8rqy+/gn1yp+XSYPbz5ok917FFgudRL32kxMF64uiyN8Nq4e30bjZxycRNsaFNGhRB+piqC6FPu4E5EJG1cDgEyOp9fFGCjcAB4mCt/W96kwyOvKlRm5RFX/+9sJW7MkhVW4BMH66qDUEUkx730jAzjX3qYGe9CRSChoPBud5eDuEgo4awjLp9Icq85Ap55g3gf2tPrG3U3krhjgzBoKdC00xky1kJXF/MylvFeBW42zNFSRQp1i1rW654zlvfHygZ5uCHdVWefajvDFtENELXCtrZ8NmMOSkA7GgrNSjjeNdjT4bv/SN/rPeZWoJibFIMvD4b/RvOphblyyAsk7m0DN0fLIkpXfdSF/yXswDd+ZAEbGyvuZ7Y8SXFlKcHOye1zFAoUAoi5MbtNyvbM=
  app: blogsync
  domain: wzdfac
  on:
    repo: WizardFactory/BlogSyncer
    branch: master
notifications:
  slack: wizardfactory:1tZT9pmQe4HiOBqPET9AdabJ
